# Azure App Service deployment configuration
# This file can be used with Azure CLI or Azure DevOps

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  # App Service Configuration
  app_name: "comicguess-backend"
  resource_group: "comicguess-rg"
  location: "East US"
  sku: "B1"  # Basic tier for cost optimization
  
  # Runtime Configuration
  runtime: "PYTHON|3.11"
  startup_command: "uvicorn main:app --host 0.0.0.0 --port 8000"
  
  # Health Check
  health_check_path: "/health"
  
  # Scaling Configuration
  min_instances: 1
  max_instances: 3
  scale_out_cpu_threshold: 70
  scale_in_cpu_threshold: 30
  
  # Application Settings (Environment Variables)
  app_settings: |
    WEBSITES_PORT=8000
    PYTHONPATH=/home/site/wwwroot
    SCM_DO_BUILD_DURING_DEPLOYMENT=true
    ENABLE_ORYX_BUILD=true
    
    # Security
    WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
    WEBSITE_HTTPLOGGING_RETENTION_DAYS=7
    
    # Performance
    WEBSITE_TIME_ZONE=UTC
    WEBSITE_RUN_FROM_PACKAGE=1