# Development Environment Configuration
name: dev
description: Development environment for testing and development

# Infrastructure
azure:
  resource_group: comicguess-dev-rg
  location: eastus
  app_service:
    name: comicguess-backend-dev
    sku: B1
    instances: 1
  cosmos_db:
    account_name: comicguess-dev-cosmos
    database_name: comicguess_dev
    throughput: 400
  storage:
    account_name: comicguessdevstorage
    tier: Standard_LRS
  function_app:
    name: comicguess-dev-functions
    sku: Y1

# Application Configuration
app:
  environment: dev
  debug: true
  log_level: DEBUG
  cors_origins:
    - http://localhost:3000
    - https://*.vercel.app
  rate_limits:
    guess_submissions: 100  # per minute
    api_requests: 1000      # per minute

# Database Configuration
database:
  partition_strategy: single
  consistency_level: Session
  backup_retention: 7  # days

# Security Configuration
security:
  jwt_expiration: 24  # hours
  session_timeout: 2  # hours
  password_policy:
    min_length: 8
    require_special: false
  rate_limiting:
    enabled: true
    strict_mode: false

# Monitoring
monitoring:
  application_insights: true
  log_retention: 30  # days
  metrics_retention: 30  # days
  alerts:
    error_rate_threshold: 10  # percent
    response_time_threshold: 5000  # ms

# Feature Flags
features:
  new_character_upload: true
  advanced_analytics: false
  beta_features: true